"""
Turkish surah name mapping utility.

Maps surah IDs to their traditional Turkish names from Diyanet convention.
Used to override English transliteration names (e.g. "Al-Baqara" → "Bakara")
stored in Qdrant payloads when the search language/locale is Turkish.

Source: quran_tr.json "translation" field (Diyanet İşleri naming convention).
"""

# Surah ID → Turkish name (Diyanet convention)
# Extracted from backend/data/quran_tr.json "translation" field.
TURKISH_SURAH_NAMES: dict[int, str] = {
    1: "Fâtiha",
    2: "Bakara",
    3: "Âl-i İmrân",
    4: "Nisâ",
    5: "Mâide",
    6: "En'âm",
    7: "A'râf",
    8: "Enfâl",
    9: "Tevbe",
    10: "Yûnus",
    11: "Hûd",
    12: "Yûsuf",
    13: "Ra'd",
    14: "İbrâhîm",
    15: "Hicr",
    16: "Nahl",
    17: "İsrâ",
    18: "Kehf",
    19: "Meryem",
    20: "Tâhâ",
    21: "Enbiyâ",
    22: "Hac",
    23: "Mü'minûn",
    24: "Nûr",
    25: "Furkân",
    26: "Şuarâ",
    27: "Neml",
    28: "Kasas",
    29: "Ankebût",
    30: "Rûm",
    31: "Lokmân",
    32: "Secde",
    33: "Ahzâb",
    34: "Sebe'",
    35: "Fâtır",
    36: "Yâsîn",
    37: "Sâffât",
    38: "Sâd",
    39: "Zümer",
    40: "Mü'min",
    41: "Fussilet",
    42: "Şûrâ",
    43: "Zuhruf",
    44: "Duhân",
    45: "Câsiye",
    46: "Ahkâf",
    47: "Muhammed",
    48: "Fetih",
    49: "Hucurât",
    50: "Kâf",
    51: "Zâriyât",
    52: "Tûr",
    53: "Necm",
    54: "Kamer",
    55: "Rahmân",
    56: "Vâkıa",
    57: "Hadîd",
    58: "Mücâdele",
    59: "Haşr",
    60: "Mümtehine",
    61: "Saf",
    62: "Cuma",
    63: "Münâfikûn",
    64: "Tegâbün",
    65: "Talâk",
    66: "Tahrîm",
    67: "Mülk",
    68: "Kalem",
    69: "Hâkka",
    70: "Meâric",
    71: "Nûh",
    72: "Cin",
    73: "Müzzemmil",
    74: "Müddessir",
    75: "Kıyâmet",
    76: "İnsân",
    77: "Mürselât",
    78: "Nebe",
    79: "Naziât",
    80: "Abese",
    81: "Tekvîr",
    82: "İnfitâr",
    83: "Mutaffifîn",
    84: "İnşikâk",
    85: "Burûc",
    86: "Târık",
    87: "A'lâ",
    88: "Gâşiye",
    89: "Fecr",
    90: "Beled",
    91: "Şems",
    92: "Leyl",
    93: "Duhâ",
    94: "İnşirâh",
    95: "Tîn",
    96: "Alak",
    97: "Kadir",
    98: "Beyyine",
    99: "Zilzâl",
    100: "Âdiyât",
    101: "Kâria",
    102: "Tekâsür",
    103: "Asr",
    104: "Hümeze",
    105: "Fîl",
    106: "Kureyş",
    107: "Maûn",
    108: "Kevser",
    109: "Kâfirûn",
    110: "Nasr",
    111: "Tebbet",
    112: "İhlâs",
    113: "Felak",
    114: "Nâs",
}


def get_turkish_surah_name(surah_id: int) -> str | None:
    """Return the traditional Turkish surah name for the given surah ID.

    Args:
        surah_id: Surah number (1-114).

    Returns:
        Turkish surah name, or None if surah_id is out of range.
    """
    return TURKISH_SURAH_NAMES.get(surah_id)
