// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CompareRequest
 *
 * Compare request schema.
 */
export type CompareRequest = {
    /**
     * Topic
     */
    topic: string;
    /**
     * Use Multi Agent
     */
    use_multi_agent?: boolean;
    /**
     * Language
     *
     * Response language (auto-detect if omitted)
     */
    language?: string | null;
};

/**
 * CompareResponse
 *
 * Compare response schema - rich format for frontend.
 */
export type CompareResponse = {
    /**
     * Topic
     */
    topic: string;
    /**
     * Essay
     */
    essay: string;
    /**
     * Paragraphs
     */
    paragraphs: Array<ParagraphData>;
    /**
     * Citations
     */
    citations: {
        [key: string]: Array<string>;
    };
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Confidence Breakdown
     */
    confidence_breakdown?: {
        [key: string]: unknown;
    } | null;
    /**
     * Total Verses
     */
    total_verses: number;
    /**
     * Total Citations
     */
    total_citations: number;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Verse Details
     */
    verse_details?: {
        [key: string]: VerseDetail;
    } | null;
    /**
     * Detected Language
     */
    detected_language?: string | null;
    /**
     * Response Language
     */
    response_language?: string | null;
};

/**
 * GoogleAuthRequest
 *
 * Google OAuth code exchange request.
 */
export type GoogleAuthRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * Redirect Uri
     */
    redirect_uri?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * KeywordSearchRequest
 */
export type KeywordSearchRequest = {
    /**
     * Query
     *
     * Arabic word or Buckwalter root
     */
    query: string;
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Per Page
     *
     * Results per page (max 200)
     */
    per_page?: number;
    /**
     * Word Filter
     *
     * Filter verses to only those containing this specific derived word (token_clean form)
     */
    word_filter?: string | null;
};

/**
 * KeywordSearchResponse
 */
export type KeywordSearchResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Root
     */
    root?: string | null;
    /**
     * Root Source
     */
    root_source: string;
    /**
     * Total Occurrences
     */
    total_occurrences?: number;
    /**
     * Unique Words
     */
    unique_words?: Array<string>;
    /**
     * Surah Distribution
     */
    surah_distribution?: Array<SurahDistItem>;
    /**
     * Verses
     */
    verses?: Array<VerseMatchItem>;
    pagination: PaginationInfo;
    /**
     * Root Buckwalter
     */
    root_buckwalter?: string | null;
    /**
     * Word Transliterations
     */
    word_transliterations?: Record<string, string>;
};

/**
 * PaginationInfo
 */
export type PaginationInfo = {
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
    /**
     * Total Verses
     */
    total_verses: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * ParagraphData
 *
 * Individual paragraph with metadata.
 */
export type ParagraphData = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Citations
     */
    citations: Array<string>;
};

/**
 * PreferencesResponse
 */
export type PreferencesResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * PreferencesUpdate
 */
export type PreferencesUpdate = {
    /**
     * Theme
     */
    theme?: string | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Default Search Source
     */
    default_search_source?: string | null;
    /**
     * Default Bible Testament
     */
    default_bible_testament?: string | null;
    /**
     * Results Per Page
     */
    results_per_page?: number | null;
    /**
     * Enable Streaming
     */
    enable_streaming?: boolean | null;
    /**
     * Enable Multi Agent
     */
    enable_multi_agent?: boolean | null;
    /**
     * Custom Settings
     */
    custom_settings?: {
        [key: string]: unknown;
    } | null;
};

/**
 * RefreshTokenRequest
 */
export type RefreshTokenRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RootListItem
 */
export type RootListItem = {
    /**
     * Root
     */
    root: string;
    /**
     * Count
     */
    count: number;
};

/**
 * RootListResponse
 */
export type RootListResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Roots
     */
    roots: Array<RootListItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Mode
     */
    mode?: string;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Language
     *
     * Response language (auto-detect if omitted)
     */
    language?: string | null;
};

/**
 * SearchResponse
 */
export type SearchResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Results
     */
    results: Array<VerseResult>;
    /**
     * Total
     */
    total: number;
    /**
     * Verse Details
     */
    verse_details?: {
        [key: string]: VerseDetail;
    } | null;
    /**
     * Detected Language
     */
    detected_language?: string | null;
};

/**
 * SurahDistItem
 */
export type SurahDistItem = {
    /**
     * Surah Id
     */
    surah_id: number;
    /**
     * Surah Name
     */
    surah_name: string;
    /**
     * Count
     */
    count: number;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Expires In
     */
    expires_in: number;
    user: UserResponse;
};

/**
 * UserCreate
 *
 * Schema for user registration.
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Name
     */
    name: string;
};

/**
 * UserLogin
 *
 * Schema for user login.
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserResponse
 *
 * Schema for user response.
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VerseDetail
 *
 * Full verse metadata for rich reference display.
 */
export type VerseDetail = {
    /**
     * Text
     */
    text: string;
    /**
     * Book Name
     */
    book_name: string;
    /**
     * Chapter
     */
    chapter: number;
    /**
     * Verse
     */
    verse: number;
    /**
     * Source
     */
    source: string;
    /**
     * Translation
     */
    translation: string;
    /**
     * Book Nr
     */
    book_nr?: number | null;
    /**
     * Surah Id
     */
    surah_id?: number | null;
    /**
     * Surah Name
     */
    surah_name?: string | null;
    /**
     * Verse Id
     */
    verse_id?: number | null;
};

/**
 * VerseMatchItem
 */
export type VerseMatchItem = {
    /**
     * Surah Id
     */
    surah_id: number;
    /**
     * Surah Name
     */
    surah_name: string;
    /**
     * Ayah Number
     */
    ayah_number: number;
    /**
     * Text Uthmani
     */
    text_uthmani: string;
    /**
     * Text Clean
     */
    text_clean: string;
    /**
     * Matched Words
     */
    matched_words: Array<string>;
};

/**
 * VerseResult
 */
export type VerseResult = {
    /**
     * Source
     */
    source: string;
    /**
     * Reference
     */
    reference: string;
    /**
     * Text
     */
    text: string;
    /**
     * Score
     */
    score: number;
};

export type RegisterApiAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterApiAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiAuthRegisterPostError = RegisterApiAuthRegisterPostErrors[keyof RegisterApiAuthRegisterPostErrors];

export type RegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RegisterApiAuthRegisterPostResponse = RegisterApiAuthRegisterPostResponses[keyof RegisterApiAuthRegisterPostResponses];

export type LoginApiAuthLoginPostData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type GoogleAuthApiAuthGooglePostData = {
    body: GoogleAuthRequest;
    path?: never;
    query?: never;
    url: '/api/auth/google';
};

export type GoogleAuthApiAuthGooglePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleAuthApiAuthGooglePostError = GoogleAuthApiAuthGooglePostErrors[keyof GoogleAuthApiAuthGooglePostErrors];

export type GoogleAuthApiAuthGooglePostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type GoogleAuthApiAuthGooglePostResponse = GoogleAuthApiAuthGooglePostResponses[keyof GoogleAuthApiAuthGooglePostResponses];

export type GetMeApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetMeApiAuthMeGetResponse = GetMeApiAuthMeGetResponses[keyof GetMeApiAuthMeGetResponses];

export type RefreshTokenApiAuthRefreshPostData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshTokenApiAuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshTokenApiAuthRefreshPostError = RefreshTokenApiAuthRefreshPostErrors[keyof RefreshTokenApiAuthRefreshPostErrors];

export type RefreshTokenApiAuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RefreshTokenApiAuthRefreshPostResponse = RefreshTokenApiAuthRefreshPostResponses[keyof RefreshTokenApiAuthRefreshPostResponses];

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRateLimitStatusApiAuthRateLimitGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/rate-limit';
};

export type GetRateLimitStatusApiAuthRateLimitGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchQuranApiSearchQuranPostData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/api/search/quran';
};

export type SearchQuranApiSearchQuranPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchQuranApiSearchQuranPostError = SearchQuranApiSearchQuranPostErrors[keyof SearchQuranApiSearchQuranPostErrors];

export type SearchQuranApiSearchQuranPostResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type SearchQuranApiSearchQuranPostResponse = SearchQuranApiSearchQuranPostResponses[keyof SearchQuranApiSearchQuranPostResponses];

export type SearchBibleApiSearchBiblePostData = {
    body: SearchRequest;
    path?: never;
    query?: {
        /**
         * Testament
         */
        testament?: string | null;
    };
    url: '/api/search/bible';
};

export type SearchBibleApiSearchBiblePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchBibleApiSearchBiblePostError = SearchBibleApiSearchBiblePostErrors[keyof SearchBibleApiSearchBiblePostErrors];

export type SearchBibleApiSearchBiblePostResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type SearchBibleApiSearchBiblePostResponse = SearchBibleApiSearchBiblePostResponses[keyof SearchBibleApiSearchBiblePostResponses];

export type ClearHistoryApiSearchHistoryDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/search/history';
};

export type ClearHistoryApiSearchHistoryDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSearchHistoryApiSearchHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search Type
         */
        search_type?: string | null;
    };
    url: '/api/search/history';
};

export type GetSearchHistoryApiSearchHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSearchHistoryApiSearchHistoryGetError = GetSearchHistoryApiSearchHistoryGetErrors[keyof GetSearchHistoryApiSearchHistoryGetErrors];

export type GetSearchHistoryApiSearchHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteData = {
    body?: never;
    path: {
        /**
         * History Id
         */
        history_id: number;
    };
    query?: never;
    url: '/api/search/history/{history_id}';
};

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteError = DeleteHistoryItemApiSearchHistoryHistoryIdDeleteErrors[keyof DeleteHistoryItemApiSearchHistoryHistoryIdDeleteErrors];

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CompareScripturesApiComparePostData = {
    body: CompareRequest;
    path?: never;
    query?: never;
    url: '/api/compare/';
};

export type CompareScripturesApiComparePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareScripturesApiComparePostError = CompareScripturesApiComparePostErrors[keyof CompareScripturesApiComparePostErrors];

export type CompareScripturesApiComparePostResponses = {
    /**
     * Successful Response
     */
    200: CompareResponse;
};

export type CompareScripturesApiComparePostResponse = CompareScripturesApiComparePostResponses[keyof CompareScripturesApiComparePostResponses];

export type StreamSearchApiStreamSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Arama sorgusu
         */
        q: string;
        /**
         * Source
         *
         * quran veya bible
         */
        source?: string;
        /**
         * Token
         *
         * JWT access token (required for SSE - EventSource can't send headers)
         */
        token: string;
        /**
         * Language
         *
         * Detected user language (ISO 639-1)
         */
        language?: string | null;
    };
    url: '/api/stream/search';
};

export type StreamSearchApiStreamSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamSearchApiStreamSearchGetError = StreamSearchApiStreamSearchGetErrors[keyof StreamSearchApiStreamSearchGetErrors];

export type StreamSearchApiStreamSearchGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamCompareApiStreamCompareGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Topic
         *
         * Karşılaştırma konusu
         */
        topic: string;
        /**
         * Token
         *
         * JWT access token (required for SSE - EventSource can't send headers)
         */
        token: string;
        /**
         * Language
         *
         * Detected user language (ISO 639-1)
         */
        language?: string | null;
    };
    url: '/api/stream/compare';
};

export type StreamCompareApiStreamCompareGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamCompareApiStreamCompareGetError = StreamCompareApiStreamCompareGetErrors[keyof StreamCompareApiStreamCompareGetErrors];

export type StreamCompareApiStreamCompareGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStatsApiAdminStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/stats';
};

export type GetStatsApiAdminStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUsersApiAdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/admin/users';
};

export type GetUsersApiAdminUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersApiAdminUsersGetError = GetUsersApiAdminUsersGetErrors[keyof GetUsersApiAdminUsersGetErrors];

export type GetUsersApiAdminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSystemInfoApiAdminSystemGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/system';
};

export type GetSystemInfoApiAdminSystemGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteUserApiAdminUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type DeleteUserApiAdminUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiAdminUsersUserIdDeleteError = DeleteUserApiAdminUsersUserIdDeleteErrors[keyof DeleteUserApiAdminUsersUserIdDeleteErrors];

export type DeleteUserApiAdminUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCollectionsApiMetadataCollectionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/metadata/collections';
};

export type GetCollectionsApiMetadataCollectionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQuranSurahsApiMetadataQuranSurahsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/metadata/quran/surahs';
};

export type GetQuranSurahsApiMetadataQuranSurahsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetData = {
    body?: never;
    path: {
        /**
         * Surah Id
         */
        surah_id: number;
    };
    query?: never;
    url: '/api/metadata/quran/surahs/{surah_id}';
};

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetError = GetSurahDetailApiMetadataQuranSurahsSurahIdGetErrors[keyof GetSurahDetailApiMetadataQuranSurahsSurahIdGetErrors];

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBibleBooksApiMetadataBibleBooksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Testament
         */
        testament?: string | null;
    };
    url: '/api/metadata/bible/books';
};

export type GetBibleBooksApiMetadataBibleBooksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBibleBooksApiMetadataBibleBooksGetError = GetBibleBooksApiMetadataBibleBooksGetErrors[keyof GetBibleBooksApiMetadataBibleBooksGetErrors];

export type GetBibleBooksApiMetadataBibleBooksGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBookDetailApiMetadataBibleBooksBookNrGetData = {
    body?: never;
    path: {
        /**
         * Book Nr
         */
        book_nr: number;
    };
    query?: never;
    url: '/api/metadata/bible/books/{book_nr}';
};

export type GetBookDetailApiMetadataBibleBooksBookNrGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBookDetailApiMetadataBibleBooksBookNrGetError = GetBookDetailApiMetadataBibleBooksBookNrGetErrors[keyof GetBookDetailApiMetadataBibleBooksBookNrGetErrors];

export type GetBookDetailApiMetadataBibleBooksBookNrGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetData = {
    body?: never;
    path: {
        /**
         * Book Nr
         */
        book_nr: number;
        /**
         * Chapter Nr
         */
        chapter_nr: number;
    };
    query?: never;
    url: '/api/metadata/bible/books/{book_nr}/chapters/{chapter_nr}';
};

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetError = GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetErrors[keyof GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetErrors];

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTestamentsApiMetadataTestamentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/metadata/testaments';
};

export type GetTestamentsApiMetadataTestamentsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResetPreferencesApiPreferencesDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/preferences/';
};

export type ResetPreferencesApiPreferencesDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPreferencesApiPreferencesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/preferences/';
};

export type GetPreferencesApiPreferencesGetResponses = {
    /**
     * Successful Response
     */
    200: PreferencesResponse;
};

export type GetPreferencesApiPreferencesGetResponse = GetPreferencesApiPreferencesGetResponses[keyof GetPreferencesApiPreferencesGetResponses];

export type UpdatePreferencesApiPreferencesPutData = {
    body: PreferencesUpdate;
    path?: never;
    query?: never;
    url: '/api/preferences/';
};

export type UpdatePreferencesApiPreferencesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePreferencesApiPreferencesPutError = UpdatePreferencesApiPreferencesPutErrors[keyof UpdatePreferencesApiPreferencesPutErrors];

export type UpdatePreferencesApiPreferencesPutResponses = {
    /**
     * Successful Response
     */
    200: PreferencesResponse;
};

export type UpdatePreferencesApiPreferencesPutResponse = UpdatePreferencesApiPreferencesPutResponses[keyof UpdatePreferencesApiPreferencesPutResponses];

export type SearchKeywordApiSearchKeywordPostData = {
    body: KeywordSearchRequest;
    path?: never;
    query?: never;
    url: '/api/search/keyword/';
};

export type SearchKeywordApiSearchKeywordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchKeywordApiSearchKeywordPostError = SearchKeywordApiSearchKeywordPostErrors[keyof SearchKeywordApiSearchKeywordPostErrors];

export type SearchKeywordApiSearchKeywordPostResponses = {
    /**
     * Successful Response
     */
    200: KeywordSearchResponse;
};

export type SearchKeywordApiSearchKeywordPostResponse = SearchKeywordApiSearchKeywordPostResponses[keyof SearchKeywordApiSearchKeywordPostResponses];

export type ListRootsApiSearchKeywordRootsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/search/keyword/roots';
};

export type ListRootsApiSearchKeywordRootsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRootsApiSearchKeywordRootsGetError = ListRootsApiSearchKeywordRootsGetErrors[keyof ListRootsApiSearchKeywordRootsGetErrors];

export type ListRootsApiSearchKeywordRootsGetResponses = {
    /**
     * Successful Response
     */
    200: RootListResponse;
};

export type ListRootsApiSearchKeywordRootsGetResponse = ListRootsApiSearchKeywordRootsGetResponses[keyof ListRootsApiSearchKeywordRootsGetResponses];

export type GetRootInfoApiSearchKeywordRootRootGetData = {
    body?: never;
    path: {
        /**
         * Root
         */
        root: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/search/keyword/root/{root}';
};

export type GetRootInfoApiSearchKeywordRootRootGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRootInfoApiSearchKeywordRootRootGetError = GetRootInfoApiSearchKeywordRootRootGetErrors[keyof GetRootInfoApiSearchKeywordRootRootGetErrors];

export type GetRootInfoApiSearchKeywordRootRootGetResponses = {
    /**
     * Successful Response
     */
    200: KeywordSearchResponse;
};

export type GetRootInfoApiSearchKeywordRootRootGetResponse = GetRootInfoApiSearchKeywordRootRootGetResponses[keyof GetRootInfoApiSearchKeywordRootRootGetResponses];

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPublicConfigApiConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetPublicConfigApiConfigGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
