// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AdminStatsData
 */
export type AdminStatsData = {
    /**
     * Total Users
     */
    total_users: number;
    /**
     * Total Searches
     */
    total_searches: number;
    /**
     * Today Searches
     */
    today_searches: number;
    /**
     * Active Users 7D
     */
    active_users_7d: number;
    /**
     * Search By Type
     */
    search_by_type: {
        [key: string]: number;
    };
};

/**
 * AdminStatsResponse
 */
export type AdminStatsResponse = {
    /**
     * Success
     */
    success?: boolean;
    data: AdminStatsData;
};

/**
 * AdminUserItem
 */
export type AdminUserItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Search Count
     */
    search_count?: number;
    /**
     * Has Google
     */
    has_google?: boolean;
};

/**
 * AdminUsersResponse
 */
export type AdminUsersResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Data
     */
    data: Array<AdminUserItem>;
    pagination: AppSchemasResponsesPaginationInfo;
};

/**
 * ApiKeyResponse
 */
export type ApiKeyResponse = {
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * BibleKeywordSearchRequest
 */
export type BibleKeywordSearchRequest = {
    /**
     * Query
     *
     * Hebrew/Aramaic word, Strong's number, or Latin transliteration
     */
    query: string;
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Per Page
     *
     * Results per page. 0 = return all verses (no pagination)
     */
    per_page?: number;
    /**
     * Language Filter
     *
     * Filter by language: 'hebrew', 'aramaic', or None for all
     */
    language_filter?: string | null;
    /**
     * Word Filter
     *
     * Filter verses to only those containing this specific word form
     */
    word_filter?: string | null;
    /**
     * Testament Filter
     *
     * Filter by testament: 'ot', 'nt', 'apocrypha', or None for all
     */
    testament_filter?: string | null;
    /**
     * Category Filter
     *
     * Filter by category: 'ot', 'nt', 'apocrypha', 'pseudepigrapha', 'gnostic', 'apostolic_fathers', or None for all
     */
    category_filter?: string | null;
};

/**
 * BibleKeywordSearchResponse
 */
export type BibleKeywordSearchResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Root
     */
    root?: string | null;
    /**
     * Root Source
     */
    root_source: string;
    /**
     * Strong Number
     */
    strong_number?: string | null;
    /**
     * Total Occurrences
     */
    total_occurrences?: number;
    /**
     * Unique Words
     */
    unique_words?: Array<string>;
    /**
     * Book Distribution
     */
    book_distribution?: Array<BookDistItem>;
    /**
     * Verses
     */
    verses?: Array<BibleVerseMatchItem>;
    pagination: AppSchemasBibleKeywordPaginationInfo;
    /**
     * Transliteration
     */
    transliteration?: string | null;
    /**
     * Word Transliterations
     */
    word_transliterations?: {
        [key: string]: string;
    };
};

/**
 * BibleRootListItem
 */
export type BibleRootListItem = {
    /**
     * Strong Number
     */
    strong_number: string | null;
    /**
     * Original Word
     */
    original_word: string | null;
    /**
     * Transliteration
     */
    transliteration: string | null;
    /**
     * Count
     */
    count: number;
};

/**
 * BibleRootListResponse
 */
export type BibleRootListResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Roots
     */
    roots: Array<BibleRootListItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
};

/**
 * BibleStatsResponse
 */
export type BibleStatsResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Total Words
     */
    total_words: number;
    /**
     * Unique Roots
     */
    unique_roots: number;
    /**
     * Total Books
     */
    total_books: number;
    /**
     * Total Verses
     */
    total_verses: number;
};

/**
 * BibleVerseMatchItem
 */
export type BibleVerseMatchItem = {
    /**
     * Book Id
     */
    book_id: number;
    /**
     * Book Name
     */
    book_name: string;
    /**
     * Chapter
     */
    chapter: number;
    /**
     * Verse
     */
    verse: number;
    /**
     * Text Original
     */
    text_original: string | null;
    /**
     * Text English
     */
    text_english: string | null;
    /**
     * Matched Words
     */
    matched_words: Array<string>;
    /**
     * Reference
     */
    reference: string;
};

/**
 * BookDistItem
 */
export type BookDistItem = {
    /**
     * Book Id
     */
    book_id: number;
    /**
     * Book Name
     */
    book_name: string;
    /**
     * Count
     */
    count: number;
};

/**
 * CacheFlushResponse
 */
export type CacheFlushResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Deleted Keys
     */
    deleted_keys: number;
};

/**
 * CompareRequest
 *
 * Compare request schema.
 */
export type CompareRequest = {
    /**
     * Topic
     */
    topic: string;
    /**
     * Use Multi Agent
     */
    use_multi_agent?: boolean;
    /**
     * Collections
     *
     * Collections to search and compare. Minimum 2 required.
     */
    collections?: Array<string>;
    /**
     * Language
     *
     * Response language (auto-detect if omitted)
     */
    language?: string | null;
    /**
     * Translator
     *
     * Quran translator (diyanet, yazir, ates, bulac, ozturk, vakfi, yildirim, yuksel)
     */
    translator?: 'diyanet' | 'yazir' | 'ates' | 'bulac' | 'ozturk' | 'vakfi' | 'yildirim' | 'yuksel' | 'arberry' | null;
    /**
     * Quran Keywords
     *
     * Optional Turkish keywords for Quran per-keyword search
     */
    quran_keywords?: Array<string> | null;
    /**
     * Bible Keywords
     *
     * Optional English keywords for Bible per-keyword search
     */
    bible_keywords?: Array<string> | null;
};

/**
 * CompareResponse
 *
 * Compare response schema - rich format for frontend.
 */
export type CompareResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Topic
     */
    topic: string;
    /**
     * Essay
     */
    essay: string;
    /**
     * Paragraphs
     */
    paragraphs: Array<ParagraphData>;
    /**
     * Citations
     */
    citations: {
        [key: string]: Array<string>;
    };
    /**
     * Confidence
     */
    confidence: number;
    /**
     * Confidence Breakdown
     */
    confidence_breakdown?: {
        [key: string]: unknown;
    } | null;
    /**
     * Total Verses
     */
    total_verses: number;
    /**
     * Total Citations
     */
    total_citations: number;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Verse Details
     */
    verse_details?: {
        [key: string]: VerseDetail;
    } | null;
    /**
     * Detected Language
     */
    detected_language?: string | null;
    /**
     * Response Language
     */
    response_language?: string | null;
};

/**
 * CrossReferenceResponse
 */
export type CrossReferenceResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Strongs Number
     */
    strongs_number: string;
    /**
     * Definition
     */
    definition?: string | null;
    /**
     * Original Word
     */
    original_word?: string | null;
    /**
     * Transliteration
     */
    transliteration?: string | null;
    /**
     * Hebrew Words
     */
    hebrew_words?: Array<CrossReferenceWord>;
    /**
     * Greek Words
     */
    greek_words?: Array<CrossReferenceWord>;
    /**
     * Total Occurrences
     */
    total_occurrences?: number;
};

/**
 * CrossReferenceWord
 */
export type CrossReferenceWord = {
    /**
     * Word
     */
    word: string;
    /**
     * Word Clean
     */
    word_clean: string;
    /**
     * Transliteration
     */
    transliteration: string;
    /**
     * Language
     */
    language: string;
    /**
     * Occurrence Count
     */
    occurrence_count: number;
};

/**
 * EnhanceRequest
 */
export type EnhanceRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Corpus
     */
    corpus?: string;
};

/**
 * EnhanceResponse
 *
 * Complete query enhancement response with keywords and metadata.
 *
 * Attributes:
 * original_query: User's original input query
 * keywords: List of extracted/suggested keywords
 * corpus: Target corpus ("quran" or "bible")
 */
export type EnhanceResponse = {
    /**
     * Original Query
     *
     * Original user query
     */
    original_query: string;
    /**
     * Keywords
     *
     * Extracted keywords
     */
    keywords?: Array<KeywordSuggestion>;
    /**
     * Corpus
     *
     * Target corpus: quran or bible
     */
    corpus?: string;
};

/**
 * ForbiddenResponse
 */
export type ForbiddenResponse = {
    /**
     * Detail
     */
    detail?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Version
     */
    version: string;
    /**
     * Event Loop
     */
    event_loop: string;
    /**
     * Qdrant
     */
    qdrant: string;
    redis: RedisStatusInfo;
};

/**
 * HistoryItem
 */
export type HistoryItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Query
     */
    query: string;
    /**
     * Search Type
     */
    search_type: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Result Count
     */
    result_count?: number | null;
};

/**
 * KeywordSearchRequest
 */
export type KeywordSearchRequest = {
    /**
     * Query
     *
     * Arabic word or Buckwalter root
     */
    query: string;
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Per Page
     *
     * Results per page. 0 = return all verses (no pagination)
     */
    per_page?: number;
    /**
     * Word Filter
     *
     * Filter verses to only those containing this specific derived word (token_clean form)
     */
    word_filter?: string | null;
};

/**
 * KeywordSearchResponse
 */
export type KeywordSearchResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Root
     */
    root?: string | null;
    /**
     * Root Source
     */
    root_source: string;
    /**
     * Total Occurrences
     */
    total_occurrences?: number;
    /**
     * Unique Words
     */
    unique_words?: Array<string>;
    /**
     * Surah Distribution
     */
    surah_distribution?: Array<SurahDistItem>;
    /**
     * Verses
     */
    verses?: Array<VerseMatchItem>;
    pagination: AppSchemasKeywordSearchPaginationInfo;
    /**
     * Root Buckwalter
     */
    root_buckwalter?: string | null;
    /**
     * Word Transliterations
     */
    word_transliterations?: {
        [key: string]: string;
    };
};

/**
 * KeywordSuggestion
 *
 * A suggested keyword extracted from a query.
 *
 * Attributes:
 * text: The keyword text
 * language: Language code ("tr" for Turkish, "en" for English, "ar" for Arabic)
 * confidence: Confidence score 0.0-1.0 (1.0 = high confidence)
 * selected: Whether keyword is selected by default in frontend
 * source: Extraction method ("llm", "rule_based", "fallback")
 */
export type KeywordSuggestion = {
    /**
     * Text
     *
     * Keyword text
     */
    text: string;
    /**
     * Language
     *
     * Language code: tr, en, ar
     */
    language?: string;
    /**
     * Confidence
     *
     * Confidence score 0.0-1.0
     */
    confidence?: number;
    /**
     * Selected
     *
     * Default selection state in UI
     */
    selected?: boolean;
    /**
     * Source
     *
     * Extraction method: llm, rule_based, fallback
     */
    source?: string;
};

/**
 * LookupVerseResult
 *
 * Single verse result with full metadata.
 *
 * Contains both Quran and Bible-specific fields. Fields are null
 * when not applicable to the source (e.g., surah_id is null for Bible verses).
 */
export type LookupVerseResult = {
    /**
     * Reference
     *
     * Canonical reference: '2:183' or 'Genesis 1:1'
     */
    reference: string;
    /**
     * Text
     *
     * Verse text in original language or translation
     */
    text: string;
    /**
     * Source
     *
     * Source collection identifier
     */
    source: 'quran' | 'bible_ot' | 'bible_nt' | 'bible_apocrypha';
    /**
     * Surah Id
     *
     * Surah number 1-114
     */
    surah_id?: number | null;
    /**
     * Surah Name
     *
     * Turkish surah name
     */
    surah_name?: string | null;
    /**
     * Verse Id
     *
     * Verse number within surah
     */
    verse_id?: number | null;
    /**
     * Arabic Text
     *
     * Original Arabic text
     */
    arabic_text?: string | null;
    /**
     * Book Id
     *
     * Book number 1-81
     */
    book_id?: number | null;
    /**
     * Book Name
     *
     * English book name
     */
    book_name?: string | null;
    /**
     * Chapter
     *
     * Chapter number
     */
    chapter?: number | null;
    /**
     * Verse
     *
     * Verse number within chapter
     */
    verse?: number | null;
};

/**
 * MessageResponse
 *
 * Generic success/message response used by delete and simple action endpoints.
 */
export type MessageResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * MetadataResponse
 */
export type MetadataResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * MorphologicalForm
 */
export type MorphologicalForm = {
    /**
     * Form Pattern
     *
     * Pattern/template (e.g., فَاعِل, مَفْعُول)
     */
    form_pattern?: string | null;
    /**
     * Form Arabic
     *
     * Arabic text of the form
     */
    form_arabic?: string | null;
    /**
     * Form Name
     *
     * Name/category of the form
     */
    form_name?: string | null;
    /**
     * Form Category
     *
     * Grammatical category (noun, verb, etc.)
     */
    form_category?: string | null;
    /**
     * Example Word
     *
     * Example word using this form
     */
    example_word?: string | null;
    /**
     * Occurrences
     *
     * Number of occurrences in Quran
     */
    occurrences?: number | null;
};

/**
 * ParagraphData
 *
 * Individual paragraph with metadata.
 */
export type ParagraphData = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Citations
     */
    citations: Array<string>;
};

/**
 * PreferencesResponse
 */
export type PreferencesResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * PreferencesUpdate
 */
export type PreferencesUpdate = {
    /**
     * Theme
     */
    theme?: string | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Default Search Source
     */
    default_search_source?: string | null;
    /**
     * Default Bible Testament
     */
    default_bible_testament?: string | null;
    /**
     * Results Per Page
     */
    results_per_page?: number | null;
    /**
     * Enable Streaming
     */
    enable_streaming?: boolean | null;
    /**
     * Enable Multi Agent
     */
    enable_multi_agent?: boolean | null;
    /**
     * Custom Settings
     */
    custom_settings?: {
        [key: string]: unknown;
    } | null;
    /**
     * Usage Purpose
     */
    usage_purpose?: string | null;
    /**
     * Arabic Proficiency
     */
    arabic_proficiency?: string | null;
    /**
     * Interests
     */
    interests?: Array<string> | null;
    /**
     * Onboarding Completed
     */
    onboarding_completed?: boolean | null;
};

/**
 * PublicConfigData
 */
export type PublicConfigData = {
    /**
     * Rate Limit Per Day
     */
    rate_limit_per_day: number;
    /**
     * Query Max Length
     */
    query_max_length: number;
    /**
     * Google Oauth Enabled
     */
    google_oauth_enabled: boolean;
};

/**
 * PublicConfigResponse
 */
export type PublicConfigResponse = {
    /**
     * Success
     */
    success?: boolean;
    data: PublicConfigData;
};

/**
 * RateLimitData
 */
export type RateLimitData = {
    /**
     * Limit
     */
    limit: number;
    /**
     * Used
     */
    used: number;
    /**
     * Remaining
     */
    remaining: number;
    /**
     * Reset At
     */
    reset_at: string;
};

/**
 * RateLimitResponse
 */
export type RateLimitResponse = {
    /**
     * Success
     */
    success?: boolean;
    data: RateLimitData;
};

/**
 * RedisStatusInfo
 */
export type RedisStatusInfo = {
    /**
     * Status
     */
    status: string;
    /**
     * Used Memory
     */
    used_memory?: string | null;
    /**
     * Connected Clients
     */
    connected_clients?: number | null;
};

/**
 * RelatedRoot
 */
export type RelatedRoot = {
    /**
     * Root
     *
     * Related root in Arabic
     */
    root: string;
    /**
     * Root Buckwalter
     *
     * Related root in Buckwalter transliteration
     */
    root_buckwalter?: string | null;
    /**
     * Meaning Hint
     *
     * Brief semantic hint for the relationship
     */
    meaning_hint?: string | null;
};

/**
 * RootEtymologyResponse
 */
export type RootEtymologyResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Id
     *
     * Etymology database ID
     */
    id: number;
    /**
     * Root
     *
     * Arabic root (e.g., كتب)
     */
    root: string;
    /**
     * Root Buckwalter
     *
     * Buckwalter Latin transliteration (e.g., ktb)
     */
    root_buckwalter: string;
    /**
     * Definition En
     *
     * English definition from Lane's Lexicon
     */
    definition_en?: string | null;
    /**
     * Definition Tr
     *
     * Turkish translation (LLM-generated)
     */
    definition_tr?: string | null;
    /**
     * Summary Tr
     *
     * Plain Turkish summary of Lane's Lexicon definition (≤200 chars)
     */
    summary_tr?: string | null;
    /**
     * Summary En
     *
     * Plain English summary of Lane's Lexicon definition (≤200 chars)
     */
    summary_en?: string | null;
    /**
     * Semantic Field
     *
     * Semantic category (e.g., 'writing', 'faith')
     */
    semantic_field?: string | null;
    /**
     * Morphological Forms
     *
     * Verb/noun patterns derived from this root (max 15)
     */
    morphological_forms?: Array<MorphologicalForm>;
    /**
     * Related Roots
     *
     * Semantically related Arabic roots (max 20)
     */
    related_roots?: Array<RelatedRoot>;
    /**
     * Quran Frequency
     *
     * Total occurrences in Quran
     */
    quran_frequency?: number;
    /**
     * Source
     *
     * Data source (e.g., 'lane', 'corpus_only')
     */
    source: string;
    /**
     * Lane Match Type
     *
     * Lane's Lexicon match quality (exact/fuzzy/none)
     */
    lane_match_type?: string | null;
    /**
     * Lane Volume
     *
     * Lane's Lexicon volume number (1-8)
     */
    lane_volume?: number | null;
    /**
     * Confidence
     *
     * Overall data confidence (high/medium/low)
     */
    confidence: string;
    /**
     * Tr Translation Source
     *
     * Turkish translation source
     */
    tr_translation_source?: string | null;
    /**
     * Tr Translation Confidence
     *
     * Turkish translation confidence score (0.0-1.0)
     */
    tr_translation_confidence?: number | null;
    /**
     * Created At
     *
     * Record creation timestamp
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp
     */
    updated_at: string;
    /**
     * Keyword Search Url
     */
    readonly keyword_search_url: string;
};

/**
 * RootListItem
 */
export type RootListItem = {
    /**
     * Root
     */
    root: string;
    /**
     * Count
     */
    count: number;
};

/**
 * RootListResponse
 */
export type RootListResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Roots
     */
    roots: Array<RootListItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
};

/**
 * SearchHistoryResponse
 */
export type SearchHistoryResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Data
     */
    data: Array<HistoryItem>;
    pagination: AppSchemasResponsesPaginationInfo;
};

/**
 * SearchRequest
 */
export type SearchRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Mode
     */
    mode?: string;
    /**
     * Top K
     */
    top_k?: number;
    /**
     * Language
     *
     * Response language (auto-detect if omitted)
     */
    language?: string | null;
    /**
     * Translator
     *
     * Quran translator (diyanet, yazir, ates, bulac, ozturk, vakfi, yildirim, yuksel)
     */
    translator?: 'diyanet' | 'yazir' | 'ates' | 'bulac' | 'ozturk' | 'vakfi' | 'yildirim' | 'yuksel' | 'arberry' | null;
};

/**
 * SearchResponse
 */
export type SearchResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Results
     */
    results: Array<SearchVerseResult>;
    /**
     * Total
     */
    total: number;
    /**
     * Verse Details
     */
    verse_details?: {
        [key: string]: VerseDetail;
    } | null;
    /**
     * Detected Language
     */
    detected_language?: string | null;
};

/**
 * SearchVerseResult
 */
export type SearchVerseResult = {
    /**
     * Source
     */
    source: string;
    /**
     * Reference
     */
    reference: string;
    /**
     * Text
     */
    text: string;
    /**
     * Score
     */
    score: number;
};

/**
 * SurahDistItem
 */
export type SurahDistItem = {
    /**
     * Surah Id
     */
    surah_id: number;
    /**
     * Surah Name
     */
    surah_name: string;
    /**
     * Count
     */
    count: number;
};

/**
 * SystemInfoData
 */
export type SystemInfoData = {
    /**
     * Python Version
     */
    python_version: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Qdrant Status
     */
    qdrant_status: string;
    /**
     * Collections Count
     */
    collections_count: number;
    /**
     * Api Status
     */
    api_status: string;
};

/**
 * SystemInfoResponse
 */
export type SystemInfoResponse = {
    /**
     * Success
     */
    success?: boolean;
    data: SystemInfoData;
};

/**
 * TranslationItem
 *
 * Single translation of a Quran verse.
 *
 * Contains the translator identifier, display name, and the actual translation text.
 */
export type TranslationItem = {
    /**
     * Translator
     *
     * Translator identifier (e.g., 'diyanet', 'yazir')
     */
    translator: string;
    /**
     * Translator Display
     *
     * Human-readable translator name (e.g., 'Diyanet İşleri', 'Elmalılı Yazır')
     */
    translator_display: string;
    /**
     * Text
     *
     * Translation text
     */
    text: string;
};

/**
 * UnauthorizedResponse
 */
export type UnauthorizedResponse = {
    /**
     * Detail
     */
    detail?: string;
};

/**
 * UserProfileResponse
 */
export type UserProfileResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerseDetail
 *
 * Full verse metadata for rich reference display.
 */
export type VerseDetail = {
    /**
     * Text
     */
    text: string;
    /**
     * Book Name
     */
    book_name: string;
    /**
     * Chapter
     */
    chapter: number;
    /**
     * Verse
     */
    verse: number;
    /**
     * Source
     */
    source: string;
    /**
     * Translation
     */
    translation: string;
    /**
     * Book Nr
     */
    book_nr?: number | null;
    /**
     * Surah Id
     */
    surah_id?: number | null;
    /**
     * Surah Name
     */
    surah_name?: string | null;
    /**
     * Verse Id
     */
    verse_id?: number | null;
};

/**
 * VerseLookupResponse
 *
 * Successful verse lookup response.
 *
 * Example:
 * {
 * "success": true,
 * "verses": [
 * {
 * "reference": "2:183",
 * "text": "Ey iman edenler, sizden önce gelenler üzerine farz kılındığı gibi...",
 * "source": "quran",
 * "surah_id": 2,
 * "surah_name": "Bakara",
 * "verse_id": 183,
 * "arabic_text": "يا أيها الذين آمنوا كتب عليكم الصيام..."
 * }
 * ],
 * "query": "2:183",
 * "count": 1
 * }
 */
export type VerseLookupResponse = {
    /**
     * Success
     *
     * Always true for successful responses
     */
    success?: boolean;
    /**
     * Verses
     *
     * List of matching verses (empty if none found)
     */
    verses: Array<LookupVerseResult>;
    /**
     * Query
     *
     * Original input query
     */
    query: string;
    /**
     * Count
     *
     * Number of verses returned
     */
    count: number;
};

/**
 * VerseMatchItem
 */
export type VerseMatchItem = {
    /**
     * Surah Id
     */
    surah_id: number;
    /**
     * Surah Name
     */
    surah_name: string;
    /**
     * Ayah Number
     */
    ayah_number: number;
    /**
     * Text Uthmani
     */
    text_uthmani: string;
    /**
     * Text Clean
     */
    text_clean: string;
    /**
     * Matched Words
     */
    matched_words: Array<string>;
};

/**
 * VerseTranslationsResponse
 *
 * Response containing all 8 Turkish translations for a single Quran verse.
 *
 * Example:
 * {
 * "success": true,
 * "surah_id": 2,
 * "verse_id": 255,
 * "surah_name": "Bakara",
 * "arabic_text": "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ...",
 * "translations": [
 * {
 * "translator": "diyanet",
 * "translator_display": "Diyanet İşleri",
 * "text": "Allah, kendisinden başka ilah olmayan..."
 * },
 * ...
 * ]
 * }
 */
export type VerseTranslationsResponse = {
    /**
     * Success
     *
     * Always true for successful responses
     */
    success?: boolean;
    /**
     * Surah Id
     *
     * Surah number (1-114)
     */
    surah_id: number;
    /**
     * Verse Id
     *
     * Verse number within the surah
     */
    verse_id: number;
    /**
     * Surah Name
     *
     * Turkish surah name
     */
    surah_name: string;
    /**
     * Arabic Text
     *
     * Original Arabic text (Uthmani script)
     */
    arabic_text: string;
    /**
     * Translations
     *
     * List of all available translations (up to 8)
     */
    translations: Array<TranslationItem>;
};

/**
 * VerseWordsResponse
 *
 * Response containing tokenized words for a specific verse.
 */
export type VerseWordsResponse = {
    /**
     * Success
     *
     * Always true for successful responses
     */
    success?: boolean;
    /**
     * Surah Id
     *
     * Surah ID (1-114)
     */
    surah_id: number;
    /**
     * Ayah Number
     *
     * Ayah number within the surah
     */
    ayah_number: number;
    /**
     * Words
     *
     * List of words in the verse
     */
    words: Array<WordItem>;
    /**
     * Word Count
     *
     * Total number of words
     */
    word_count: number;
};

/**
 * WordItem
 *
 * Individual word item with morphological and etymology metadata.
 */
export type WordItem = {
    /**
     * Position
     *
     * Position of word in verse (0-indexed)
     */
    position: number;
    /**
     * Token
     *
     * Original Arabic token
     */
    token?: string | null;
    /**
     * Token Clean
     *
     * Cleaned Arabic token (no diacritics)
     */
    token_clean?: string | null;
    /**
     * Root
     *
     * Arabic root (if available)
     */
    root?: string | null;
    /**
     * Root Buckwalter
     *
     * Root in Buckwalter transliteration
     */
    root_buckwalter?: string | null;
    /**
     * Lemma
     *
     * Lemma (base form)
     */
    lemma?: string | null;
    /**
     * Pos Tag
     *
     * Part-of-speech tag
     */
    pos_tag?: string | null;
    /**
     * Has Etymology
     *
     * Whether etymology data exists for this root
     */
    has_etymology: boolean;
};

/**
 * PaginationInfo
 */
export type AppSchemasBibleKeywordPaginationInfo = {
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
    /**
     * Total Verses
     */
    total_verses: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * PaginationInfo
 */
export type AppSchemasKeywordSearchPaginationInfo = {
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
    /**
     * Total Verses
     */
    total_verses: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * PaginationInfo
 *
 * Pagination metadata returned alongside paginated list endpoints.
 */
export type AppSchemasResponsesPaginationInfo = {
    /**
     * Page
     */
    page: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Total Items
     */
    total_items: number;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Has Next
     */
    has_next: boolean;
    /**
     * Has Prev
     */
    has_prev: boolean;
};

/**
 * SearchStatusEvent
 *
 * Pipeline status update during search processing.
 */
export type SearchStatusEvent = {
    /**
     * Status
     *
     * Current pipeline stage
     */
    status: 'searching' | 'found' | 'generating' | 'translating';
    /**
     * Message
     *
     * Human-readable status message (absent when status='found')
     */
    message?: string | null;
    /**
     * Count
     *
     * Number of search results found (only present when status='found')
     */
    count?: number | null;
};

/**
 * SearchTokenEvent
 *
 * Single answer token streamed word-by-word from the AI answer generation.
 */
export type SearchTokenEvent = {
    /**
     * Type
     */
    type?: 'token';
    /**
     * Content
     *
     * A single word/token of the generated answer, with trailing space
     */
    content: string;
};

/**
 * SearchCitationsEvent
 *
 * Citation list sent once after all answer tokens have been streamed.
 */
export type SearchCitationsEvent = {
    /**
     * Citations
     *
     * Array of citation reference strings
     */
    citations: Array<string>;
};

/**
 * SearchVerseDetailsEvent
 *
 * Verse metadata map sent before the final complete event.
 */
export type SearchVerseDetailsEvent = {
    /**
     * Verse Details
     *
     * Map of verse reference string to verse metadata object (schema varies by source collection)
     */
    verse_details: {
        [key: string]: unknown;
    };
};

/**
 * SearchCompleteEvent
 *
 * Final event for /api/stream/search — signals stream completion with full result data.
 */
export type SearchCompleteEvent = {
    /**
     * Type
     */
    type?: 'complete';
    /**
     * Aggregated result; absent in error cases where a preceding error event was sent
     */
    result?: SearchCompleteResult | null;
};

/**
 * SearchCompleteResult
 *
 * Aggregated result payload included in the search stream's final complete event.
 */
export type SearchCompleteResult = {
    /**
     * Results
     *
     * All retrieved search result items
     */
    results: Array<SearchResultItem>;
    /**
     * Answer
     *
     * Complete AI-generated answer text (after optional translation)
     */
    answer: string;
    /**
     * Citations
     *
     * Array of citation reference strings
     */
    citations: Array<string>;
};

/**
 * SearchResultItem
 *
 * A single search result item included in the complete event payload.
 */
export type SearchResultItem = {
    /**
     * Source
     *
     * Source collection identifier (e.g., 'quran', 'bible_ot', 'bible_nt', 'bible_apocrypha')
     */
    source: string;
    /**
     * Reference
     *
     * Verse reference string (e.g., 'Al-Fatiha:1' or 'Genesis 1:1')
     */
    reference: string;
    /**
     * Text
     *
     * Verse text content
     */
    text: string;
    /**
     * Score
     *
     * Relevance score from the vector search
     */
    score: number;
};

/**
 * CompareProgressEvent
 *
 * Real-time progress update from the multi-agent comparative analysis pipeline.
 */
export type CompareProgressEvent = {
    /**
     * Type
     */
    type?: 'progress';
    /**
     * Step
     *
     * Machine-readable step identifier emitted by the pipeline (e.g., 'pipeline_started', 'building_verse_details', 'translating_response')
     */
    step: string;
    /**
     * Message
     *
     * Human-readable progress message
     */
    message: string;
};

/**
 * CompareVerseDetailsEvent
 *
 * Verse metadata map emitted before paragraph streaming begins.
 */
export type CompareVerseDetailsEvent = {
    /**
     * Verse Details
     *
     * Map of verse reference string to verse metadata object (schema varies by source collection)
     */
    verse_details: {
        [key: string]: unknown;
    };
};

/**
 * CompareParagraphEvent
 *
 * A single structured paragraph streamed from the multi-agent comparative essay.
 */
export type CompareParagraphEvent = {
    /**
     * Type
     */
    type?: 'paragraph';
    /**
     * Paragraph title and markdown content
     */
    data: CompareParagraphData;
};

/**
 * CompareParagraphData
 *
 * Content payload for a single comparative analysis paragraph.
 */
export type CompareParagraphData = {
    /**
     * Title
     *
     * Section title (e.g., 'Introduction', 'Quran Perspective')
     */
    title: string;
    /**
     * Content
     *
     * Full markdown text content of the paragraph
     */
    content: string;
};

/**
 * CompareStatsEvent
 *
 * Statistics event sent after all paragraphs have been streamed.
 */
export type CompareStatsEvent = {
    /**
     * Type
     */
    type?: 'stats';
    /**
     * Pipeline statistics and performance metrics
     */
    data: CompareStatsData;
};

/**
 * CompareStatsData
 *
 * Statistical summary collected at the end of the compare pipeline.
 */
export type CompareStatsData = {
    /**
     * Confidence
     *
     * Overall confidence score (0.0–1.0)
     */
    confidence: number;
    /**
     * Confidence Breakdown
     *
     * Per-agent confidence breakdown dict (present when available)
     */
    confidence_breakdown?: {
        [key: string]: unknown;
    } | null;
    /**
     * Latency Ms
     *
     * Total pipeline latency in milliseconds
     */
    latency_ms: number;
    /**
     * Total Verses
     *
     * Total number of verses retrieved across all collections
     */
    total_verses: number;
    /**
     * Total Citations
     *
     * Total number of citations in the generated essay
     */
    total_citations: number;
};

/**
 * SSECompleteEvent
 *
 * Signals end of the SSE stream (emitted by /stream/compare and error paths of /stream/search).
 */
export type SseCompleteEvent = {
    /**
     * Type
     */
    type?: 'complete';
};

/**
 * SSEErrorEvent
 *
 * Error event — the stream should be considered terminated after this.
 */
export type SseErrorEvent = {
    /**
     * Error
     *
     * Human-readable error description
     */
    error: string;
};

/**
 * RootEtymologyResponse
 */
export type RootEtymologyResponseWritable = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Id
     *
     * Etymology database ID
     */
    id: number;
    /**
     * Root
     *
     * Arabic root (e.g., كتب)
     */
    root: string;
    /**
     * Root Buckwalter
     *
     * Buckwalter Latin transliteration (e.g., ktb)
     */
    root_buckwalter: string;
    /**
     * Definition En
     *
     * English definition from Lane's Lexicon
     */
    definition_en?: string | null;
    /**
     * Definition Tr
     *
     * Turkish translation (LLM-generated)
     */
    definition_tr?: string | null;
    /**
     * Summary Tr
     *
     * Plain Turkish summary of Lane's Lexicon definition (≤200 chars)
     */
    summary_tr?: string | null;
    /**
     * Summary En
     *
     * Plain English summary of Lane's Lexicon definition (≤200 chars)
     */
    summary_en?: string | null;
    /**
     * Semantic Field
     *
     * Semantic category (e.g., 'writing', 'faith')
     */
    semantic_field?: string | null;
    /**
     * Morphological Forms
     *
     * Verb/noun patterns derived from this root (max 15)
     */
    morphological_forms?: Array<MorphologicalForm>;
    /**
     * Related Roots
     *
     * Semantically related Arabic roots (max 20)
     */
    related_roots?: Array<RelatedRoot>;
    /**
     * Quran Frequency
     *
     * Total occurrences in Quran
     */
    quran_frequency?: number;
    /**
     * Source
     *
     * Data source (e.g., 'lane', 'corpus_only')
     */
    source: string;
    /**
     * Lane Match Type
     *
     * Lane's Lexicon match quality (exact/fuzzy/none)
     */
    lane_match_type?: string | null;
    /**
     * Lane Volume
     *
     * Lane's Lexicon volume number (1-8)
     */
    lane_volume?: number | null;
    /**
     * Confidence
     *
     * Overall data confidence (high/medium/low)
     */
    confidence: string;
    /**
     * Tr Translation Source
     *
     * Turkish translation source
     */
    tr_translation_source?: string | null;
    /**
     * Tr Translation Confidence
     *
     * Turkish translation confidence score (0.0-1.0)
     */
    tr_translation_confidence?: number | null;
    /**
     * Created At
     *
     * Record creation timestamp
     */
    created_at: string;
    /**
     * Updated At
     *
     * Last update timestamp
     */
    updated_at: string;
};

export type GetMeApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeApiAuthMeGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
};

export type GetMeApiAuthMeGetError = GetMeApiAuthMeGetErrors[keyof GetMeApiAuthMeGetErrors];

export type GetMeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetMeApiAuthMeGetResponse = GetMeApiAuthMeGetResponses[keyof GetMeApiAuthMeGetResponses];

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutApiAuthLogoutPostErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
};

export type LogoutApiAuthLogoutPostError = LogoutApiAuthLogoutPostErrors[keyof LogoutApiAuthLogoutPostErrors];

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type LogoutApiAuthLogoutPostResponse = LogoutApiAuthLogoutPostResponses[keyof LogoutApiAuthLogoutPostResponses];

export type GetRateLimitStatusApiAuthRateLimitGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/rate-limit';
};

export type GetRateLimitStatusApiAuthRateLimitGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
};

export type GetRateLimitStatusApiAuthRateLimitGetError = GetRateLimitStatusApiAuthRateLimitGetErrors[keyof GetRateLimitStatusApiAuthRateLimitGetErrors];

export type GetRateLimitStatusApiAuthRateLimitGetResponses = {
    /**
     * Successful Response
     */
    200: RateLimitResponse;
};

export type GetRateLimitStatusApiAuthRateLimitGetResponse = GetRateLimitStatusApiAuthRateLimitGetResponses[keyof GetRateLimitStatusApiAuthRateLimitGetResponses];

export type GenerateApiKeyApiAuthApiKeyPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/api-key';
};

export type GenerateApiKeyApiAuthApiKeyPostErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
};

export type GenerateApiKeyApiAuthApiKeyPostError = GenerateApiKeyApiAuthApiKeyPostErrors[keyof GenerateApiKeyApiAuthApiKeyPostErrors];

export type GenerateApiKeyApiAuthApiKeyPostResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyResponse;
};

export type GenerateApiKeyApiAuthApiKeyPostResponse = GenerateApiKeyApiAuthApiKeyPostResponses[keyof GenerateApiKeyApiAuthApiKeyPostResponses];

export type SearchQuranApiSearchQuranPostData = {
    body: SearchRequest;
    path?: never;
    query?: {
        /**
         * Lang
         *
         * Override locale (tr, en)
         */
        lang?: string | null;
    };
    url: '/api/search/quran';
};

export type SearchQuranApiSearchQuranPostErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchQuranApiSearchQuranPostError = SearchQuranApiSearchQuranPostErrors[keyof SearchQuranApiSearchQuranPostErrors];

export type SearchQuranApiSearchQuranPostResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type SearchQuranApiSearchQuranPostResponse = SearchQuranApiSearchQuranPostResponses[keyof SearchQuranApiSearchQuranPostResponses];

export type SearchBibleApiSearchBiblePostData = {
    body: SearchRequest;
    path?: never;
    query?: {
        /**
         * Testament
         */
        testament?: string | null;
        /**
         * Lang
         *
         * Override locale (tr, en)
         */
        lang?: string | null;
    };
    url: '/api/search/bible';
};

export type SearchBibleApiSearchBiblePostErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchBibleApiSearchBiblePostError = SearchBibleApiSearchBiblePostErrors[keyof SearchBibleApiSearchBiblePostErrors];

export type SearchBibleApiSearchBiblePostResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type SearchBibleApiSearchBiblePostResponse = SearchBibleApiSearchBiblePostResponses[keyof SearchBibleApiSearchBiblePostResponses];

export type ClearHistoryApiSearchHistoryDeleteData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lang
         *
         * Override locale (tr, en)
         */
        lang?: string | null;
    };
    url: '/api/search/history';
};

export type ClearHistoryApiSearchHistoryDeleteErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClearHistoryApiSearchHistoryDeleteError = ClearHistoryApiSearchHistoryDeleteErrors[keyof ClearHistoryApiSearchHistoryDeleteErrors];

export type ClearHistoryApiSearchHistoryDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ClearHistoryApiSearchHistoryDeleteResponse = ClearHistoryApiSearchHistoryDeleteResponses[keyof ClearHistoryApiSearchHistoryDeleteResponses];

export type GetSearchHistoryApiSearchHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search Type
         */
        search_type?: string | null;
    };
    url: '/api/search/history';
};

export type GetSearchHistoryApiSearchHistoryGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSearchHistoryApiSearchHistoryGetError = GetSearchHistoryApiSearchHistoryGetErrors[keyof GetSearchHistoryApiSearchHistoryGetErrors];

export type GetSearchHistoryApiSearchHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: SearchHistoryResponse;
};

export type GetSearchHistoryApiSearchHistoryGetResponse = GetSearchHistoryApiSearchHistoryGetResponses[keyof GetSearchHistoryApiSearchHistoryGetResponses];

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteData = {
    body?: never;
    path: {
        /**
         * History Id
         */
        history_id: number;
    };
    query?: {
        /**
         * Lang
         *
         * Override locale (tr, en)
         */
        lang?: string | null;
    };
    url: '/api/search/history/{history_id}';
};

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteError = DeleteHistoryItemApiSearchHistoryHistoryIdDeleteErrors[keyof DeleteHistoryItemApiSearchHistoryHistoryIdDeleteErrors];

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteHistoryItemApiSearchHistoryHistoryIdDeleteResponse = DeleteHistoryItemApiSearchHistoryHistoryIdDeleteResponses[keyof DeleteHistoryItemApiSearchHistoryHistoryIdDeleteResponses];

export type EnhanceQueryApiSearchEnhancePostData = {
    body: EnhanceRequest;
    path?: never;
    query?: never;
    url: '/api/search/enhance';
};

export type EnhanceQueryApiSearchEnhancePostErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnhanceQueryApiSearchEnhancePostError = EnhanceQueryApiSearchEnhancePostErrors[keyof EnhanceQueryApiSearchEnhancePostErrors];

export type EnhanceQueryApiSearchEnhancePostResponses = {
    /**
     * Successful Response
     */
    200: EnhanceResponse;
};

export type EnhanceQueryApiSearchEnhancePostResponse = EnhanceQueryApiSearchEnhancePostResponses[keyof EnhanceQueryApiSearchEnhancePostResponses];

export type GetEtymologyApiEtymologyRootGetData = {
    body?: never;
    path: {
        /**
         * Root
         */
        root: string;
    };
    query?: never;
    url: '/api/etymology/{root}';
};

export type GetEtymologyApiEtymologyRootGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEtymologyApiEtymologyRootGetError = GetEtymologyApiEtymologyRootGetErrors[keyof GetEtymologyApiEtymologyRootGetErrors];

export type GetEtymologyApiEtymologyRootGetResponses = {
    /**
     * Successful Response
     */
    200: RootEtymologyResponse;
};

export type GetEtymologyApiEtymologyRootGetResponse = GetEtymologyApiEtymologyRootGetResponses[keyof GetEtymologyApiEtymologyRootGetResponses];

export type CompareScripturesApiComparePostData = {
    body: CompareRequest;
    path?: never;
    query?: {
        /**
         * Lang
         *
         * Override locale (tr, en)
         */
        lang?: string | null;
    };
    url: '/api/compare/';
};

export type CompareScripturesApiComparePostErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareScripturesApiComparePostError = CompareScripturesApiComparePostErrors[keyof CompareScripturesApiComparePostErrors];

export type CompareScripturesApiComparePostResponses = {
    /**
     * Successful Response
     */
    200: CompareResponse;
};

export type CompareScripturesApiComparePostResponse = CompareScripturesApiComparePostResponses[keyof CompareScripturesApiComparePostResponses];

export type StreamSearchApiStreamSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Arama sorgusu
         */
        q: string;
        /**
         * Source
         *
         * Source collection: quran, ot, nt, or apocrypha
         */
        source?: 'quran' | 'ot' | 'nt' | 'apocrypha';
        /**
         * Language
         *
         * Detected user language (ISO 639-1)
         */
        language?: string | null;
        /**
         * Translator
         *
         * Quran translator (diyanet, yazir, ates, bulac, ozturk, vakfi, yildirim, yuksel)
         */
        translator?: 'diyanet' | 'yazir' | 'ates' | 'bulac' | 'ozturk' | 'vakfi' | 'yildirim' | 'yuksel' | 'arberry' | null;
        /**
         * Lang
         *
         * Override locale (tr, en)
         */
        lang?: string | null;
    };
    url: '/api/stream/search';
};

export type StreamSearchApiStreamSearchGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamSearchApiStreamSearchGetError = StreamSearchApiStreamSearchGetErrors[keyof StreamSearchApiStreamSearchGetErrors];

export type StreamSearchApiStreamSearchGetResponses = {
    /**
     * Server-Sent Events stream of search results and AI answer tokens.
     *
     * ## SSE Event Types
     *
     * Each `data:` line contains a JSON object with one of these shapes:
     *
     * | Event | Discriminator | Description |
     * |-------|--------------|-------------|
     * | Status | `status` field | Pipeline progress (`searching` → `found` → `generating` → `translating`) |
     * | Token | `type: "token"` | Single word of the AI-generated answer |
     * | Citations | `citations` field | Array of citation reference strings |
     * | Verse Details | `verse_details` field | Map of reference → verse metadata |
     * | Complete | `type: "complete"` | Final aggregated result with answer, results, and citations |
     * | Error | `type: "error"` | Error message with optional `error_code` (e.g. `auth_required`) |
     *
     */
    200: unknown;
};

export type StreamCompareApiStreamCompareGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Topic
         *
         * Karşılaştırma konusu
         */
        topic: string;
        /**
         * Collections
         *
         * Comma-separated list of collections to search (minimum 2)
         */
        collections?: string;
        /**
         * Language
         *
         * Detected user language (ISO 639-1)
         */
        language?: string | null;
        /**
         * Translator
         *
         * Quran translator (diyanet, yazir, ates, bulac, ozturk, vakfi, yildirim, yuksel)
         */
        translator?: 'diyanet' | 'yazir' | 'ates' | 'bulac' | 'ozturk' | 'vakfi' | 'yildirim' | 'yuksel' | 'arberry' | null;
        /**
         * Lang
         *
         * Override locale (tr, en)
         */
        lang?: string | null;
    };
    url: '/api/stream/compare';
};

export type StreamCompareApiStreamCompareGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamCompareApiStreamCompareGetError = StreamCompareApiStreamCompareGetErrors[keyof StreamCompareApiStreamCompareGetErrors];

export type StreamCompareApiStreamCompareGetResponses = {
    /**
     * Server-Sent Events stream of multi-agent comparative analysis.
     *
     * ## SSE Event Types
     *
     * Each `data:` line contains a JSON object with one of these shapes:
     *
     * | Event | Discriminator | Description |
     * |-------|--------------|-------------|
     * | Progress | `type: "progress"` | Pipeline step updates with machine-readable step ID |
     * | Verse Details | `verse_details` field | Map of reference → verse metadata |
     * | Paragraph | `type: "paragraph"` | Structured essay paragraph with title and markdown content |
     * | Stats | `type: "stats"` | Confidence score, latency, verse/citation counts |
     * | Complete | `type: "complete"` | Signals end of stream |
     * | Error | `type: "error"` | Error message with optional `error_code` (e.g. `auth_required`) |
     *
     */
    200: unknown;
};

export type GetStatsApiAdminStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/stats';
};

export type GetStatsApiAdminStatsGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Admin access required
     */
    403: ForbiddenResponse;
};

export type GetStatsApiAdminStatsGetError = GetStatsApiAdminStatsGetErrors[keyof GetStatsApiAdminStatsGetErrors];

export type GetStatsApiAdminStatsGetResponses = {
    /**
     * Successful Response
     */
    200: AdminStatsResponse;
};

export type GetStatsApiAdminStatsGetResponse = GetStatsApiAdminStatsGetResponses[keyof GetStatsApiAdminStatsGetResponses];

export type GetUsersApiAdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/admin/users';
};

export type GetUsersApiAdminUsersGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Admin access required
     */
    403: ForbiddenResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersApiAdminUsersGetError = GetUsersApiAdminUsersGetErrors[keyof GetUsersApiAdminUsersGetErrors];

export type GetUsersApiAdminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: AdminUsersResponse;
};

export type GetUsersApiAdminUsersGetResponse = GetUsersApiAdminUsersGetResponses[keyof GetUsersApiAdminUsersGetResponses];

export type GetSystemInfoApiAdminSystemGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/system';
};

export type GetSystemInfoApiAdminSystemGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Admin access required
     */
    403: ForbiddenResponse;
};

export type GetSystemInfoApiAdminSystemGetError = GetSystemInfoApiAdminSystemGetErrors[keyof GetSystemInfoApiAdminSystemGetErrors];

export type GetSystemInfoApiAdminSystemGetResponses = {
    /**
     * Successful Response
     */
    200: SystemInfoResponse;
};

export type GetSystemInfoApiAdminSystemGetResponse = GetSystemInfoApiAdminSystemGetResponses[keyof GetSystemInfoApiAdminSystemGetResponses];

export type DeleteUserApiAdminUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: {
        /**
         * Lang
         *
         * Override locale (tr, en)
         */
        lang?: string | null;
    };
    url: '/api/admin/users/{user_id}';
};

export type DeleteUserApiAdminUsersUserIdDeleteErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Admin access required
     */
    403: ForbiddenResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiAdminUsersUserIdDeleteError = DeleteUserApiAdminUsersUserIdDeleteErrors[keyof DeleteUserApiAdminUsersUserIdDeleteErrors];

export type DeleteUserApiAdminUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type DeleteUserApiAdminUsersUserIdDeleteResponse = DeleteUserApiAdminUsersUserIdDeleteResponses[keyof DeleteUserApiAdminUsersUserIdDeleteResponses];

export type FlushSearchCacheApiAdminCacheFlushPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/cache/flush';
};

export type FlushSearchCacheApiAdminCacheFlushPostErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Admin access required
     */
    403: ForbiddenResponse;
};

export type FlushSearchCacheApiAdminCacheFlushPostError = FlushSearchCacheApiAdminCacheFlushPostErrors[keyof FlushSearchCacheApiAdminCacheFlushPostErrors];

export type FlushSearchCacheApiAdminCacheFlushPostResponses = {
    /**
     * Successful Response
     */
    200: CacheFlushResponse;
};

export type FlushSearchCacheApiAdminCacheFlushPostResponse = FlushSearchCacheApiAdminCacheFlushPostResponses[keyof FlushSearchCacheApiAdminCacheFlushPostResponses];

export type GetCollectionsApiMetadataCollectionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/metadata/collections';
};

export type GetCollectionsApiMetadataCollectionsGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataResponse;
};

export type GetCollectionsApiMetadataCollectionsGetResponse = GetCollectionsApiMetadataCollectionsGetResponses[keyof GetCollectionsApiMetadataCollectionsGetResponses];

export type GetQuranSurahsApiMetadataQuranSurahsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/metadata/quran/surahs';
};

export type GetQuranSurahsApiMetadataQuranSurahsGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataResponse;
};

export type GetQuranSurahsApiMetadataQuranSurahsGetResponse = GetQuranSurahsApiMetadataQuranSurahsGetResponses[keyof GetQuranSurahsApiMetadataQuranSurahsGetResponses];

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetData = {
    body?: never;
    path: {
        /**
         * Surah Id
         */
        surah_id: number;
    };
    query?: {
        /**
         * Translator
         *
         * Quran translator (diyanet, yazir, ates, bulac, ozturk, vakfi, yildirim, yuksel)
         */
        translator?: 'diyanet' | 'yazir' | 'ates' | 'bulac' | 'ozturk' | 'vakfi' | 'yildirim' | 'yuksel' | 'arberry';
    };
    url: '/api/metadata/quran/surahs/{surah_id}';
};

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetError = GetSurahDetailApiMetadataQuranSurahsSurahIdGetErrors[keyof GetSurahDetailApiMetadataQuranSurahsSurahIdGetErrors];

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataResponse;
};

export type GetSurahDetailApiMetadataQuranSurahsSurahIdGetResponse = GetSurahDetailApiMetadataQuranSurahsSurahIdGetResponses[keyof GetSurahDetailApiMetadataQuranSurahsSurahIdGetResponses];

export type GetBibleBooksApiMetadataBibleBooksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Testament
         */
        testament?: string | null;
    };
    url: '/api/metadata/bible/books';
};

export type GetBibleBooksApiMetadataBibleBooksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBibleBooksApiMetadataBibleBooksGetError = GetBibleBooksApiMetadataBibleBooksGetErrors[keyof GetBibleBooksApiMetadataBibleBooksGetErrors];

export type GetBibleBooksApiMetadataBibleBooksGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataResponse;
};

export type GetBibleBooksApiMetadataBibleBooksGetResponse = GetBibleBooksApiMetadataBibleBooksGetResponses[keyof GetBibleBooksApiMetadataBibleBooksGetResponses];

export type GetBookDetailApiMetadataBibleBooksBookNrGetData = {
    body?: never;
    path: {
        /**
         * Book Nr
         */
        book_nr: number;
    };
    query?: never;
    url: '/api/metadata/bible/books/{book_nr}';
};

export type GetBookDetailApiMetadataBibleBooksBookNrGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBookDetailApiMetadataBibleBooksBookNrGetError = GetBookDetailApiMetadataBibleBooksBookNrGetErrors[keyof GetBookDetailApiMetadataBibleBooksBookNrGetErrors];

export type GetBookDetailApiMetadataBibleBooksBookNrGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataResponse;
};

export type GetBookDetailApiMetadataBibleBooksBookNrGetResponse = GetBookDetailApiMetadataBibleBooksBookNrGetResponses[keyof GetBookDetailApiMetadataBibleBooksBookNrGetResponses];

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetData = {
    body?: never;
    path: {
        /**
         * Book Nr
         */
        book_nr: number;
        /**
         * Chapter Nr
         */
        chapter_nr: number;
    };
    query?: never;
    url: '/api/metadata/bible/books/{book_nr}/chapters/{chapter_nr}';
};

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetError = GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetErrors[keyof GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetErrors];

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataResponse;
};

export type GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetResponse = GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetResponses[keyof GetChapterVersesApiMetadataBibleBooksBookNrChaptersChapterNrGetResponses];

export type GetTestamentsApiMetadataTestamentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/metadata/testaments';
};

export type GetTestamentsApiMetadataTestamentsGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataResponse;
};

export type GetTestamentsApiMetadataTestamentsGetResponse = GetTestamentsApiMetadataTestamentsGetResponses[keyof GetTestamentsApiMetadataTestamentsGetResponses];

export type GetTranslatorsApiMetadataTranslatorsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/metadata/translators';
};

export type GetTranslatorsApiMetadataTranslatorsGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataResponse;
};

export type GetTranslatorsApiMetadataTranslatorsGetResponse = GetTranslatorsApiMetadataTranslatorsGetResponses[keyof GetTranslatorsApiMetadataTranslatorsGetResponses];

export type GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetData = {
    body?: never;
    path: {
        /**
         * Surah Id
         */
        surah_id: number;
        /**
         * Verse Id
         */
        verse_id: number;
    };
    query?: never;
    url: '/api/metadata/quran/verses/{surah_id}/{verse_id}/translations';
};

export type GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetError = GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetErrors[keyof GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetErrors];

export type GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetResponses = {
    /**
     * Successful Response
     */
    200: VerseTranslationsResponse;
};

export type GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetResponse = GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetResponses[keyof GetVerseTranslationsApiMetadataQuranVersesSurahIdVerseIdTranslationsGetResponses];

export type ResetPreferencesApiPreferencesDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/preferences/';
};

export type ResetPreferencesApiPreferencesDeleteErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
};

export type ResetPreferencesApiPreferencesDeleteError = ResetPreferencesApiPreferencesDeleteErrors[keyof ResetPreferencesApiPreferencesDeleteErrors];

export type ResetPreferencesApiPreferencesDeleteResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type ResetPreferencesApiPreferencesDeleteResponse = ResetPreferencesApiPreferencesDeleteResponses[keyof ResetPreferencesApiPreferencesDeleteResponses];

export type GetPreferencesApiPreferencesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/preferences/';
};

export type GetPreferencesApiPreferencesGetErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
};

export type GetPreferencesApiPreferencesGetError = GetPreferencesApiPreferencesGetErrors[keyof GetPreferencesApiPreferencesGetErrors];

export type GetPreferencesApiPreferencesGetResponses = {
    /**
     * Successful Response
     */
    200: PreferencesResponse;
};

export type GetPreferencesApiPreferencesGetResponse = GetPreferencesApiPreferencesGetResponses[keyof GetPreferencesApiPreferencesGetResponses];

export type UpdatePreferencesApiPreferencesPutData = {
    body: PreferencesUpdate;
    path?: never;
    query?: never;
    url: '/api/preferences/';
};

export type UpdatePreferencesApiPreferencesPutErrors = {
    /**
     * Not authenticated
     */
    401: UnauthorizedResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePreferencesApiPreferencesPutError = UpdatePreferencesApiPreferencesPutErrors[keyof UpdatePreferencesApiPreferencesPutErrors];

export type UpdatePreferencesApiPreferencesPutResponses = {
    /**
     * Successful Response
     */
    200: PreferencesResponse;
};

export type UpdatePreferencesApiPreferencesPutResponse = UpdatePreferencesApiPreferencesPutResponses[keyof UpdatePreferencesApiPreferencesPutResponses];

export type SearchKeywordApiSearchKeywordPostData = {
    body: KeywordSearchRequest;
    path?: never;
    query?: never;
    url: '/api/search/keyword/';
};

export type SearchKeywordApiSearchKeywordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchKeywordApiSearchKeywordPostError = SearchKeywordApiSearchKeywordPostErrors[keyof SearchKeywordApiSearchKeywordPostErrors];

export type SearchKeywordApiSearchKeywordPostResponses = {
    /**
     * Successful Response
     */
    200: KeywordSearchResponse;
};

export type SearchKeywordApiSearchKeywordPostResponse = SearchKeywordApiSearchKeywordPostResponses[keyof SearchKeywordApiSearchKeywordPostResponses];

export type ListRootsApiSearchKeywordRootsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/search/keyword/roots';
};

export type ListRootsApiSearchKeywordRootsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRootsApiSearchKeywordRootsGetError = ListRootsApiSearchKeywordRootsGetErrors[keyof ListRootsApiSearchKeywordRootsGetErrors];

export type ListRootsApiSearchKeywordRootsGetResponses = {
    /**
     * Successful Response
     */
    200: RootListResponse;
};

export type ListRootsApiSearchKeywordRootsGetResponse = ListRootsApiSearchKeywordRootsGetResponses[keyof ListRootsApiSearchKeywordRootsGetResponses];

export type GetRootInfoApiSearchKeywordRootRootGetData = {
    body?: never;
    path: {
        /**
         * Root
         */
        root: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/search/keyword/root/{root}';
};

export type GetRootInfoApiSearchKeywordRootRootGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRootInfoApiSearchKeywordRootRootGetError = GetRootInfoApiSearchKeywordRootRootGetErrors[keyof GetRootInfoApiSearchKeywordRootRootGetErrors];

export type GetRootInfoApiSearchKeywordRootRootGetResponses = {
    /**
     * Successful Response
     */
    200: KeywordSearchResponse;
};

export type GetRootInfoApiSearchKeywordRootRootGetResponse = GetRootInfoApiSearchKeywordRootRootGetResponses[keyof GetRootInfoApiSearchKeywordRootRootGetResponses];

export type SearchBibleKeywordApiKeywordSearchBiblePostData = {
    body: BibleKeywordSearchRequest;
    path?: never;
    query?: never;
    url: '/api/keyword-search/bible/';
};

export type SearchBibleKeywordApiKeywordSearchBiblePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchBibleKeywordApiKeywordSearchBiblePostError = SearchBibleKeywordApiKeywordSearchBiblePostErrors[keyof SearchBibleKeywordApiKeywordSearchBiblePostErrors];

export type SearchBibleKeywordApiKeywordSearchBiblePostResponses = {
    /**
     * Successful Response
     */
    200: BibleKeywordSearchResponse;
};

export type SearchBibleKeywordApiKeywordSearchBiblePostResponse = SearchBibleKeywordApiKeywordSearchBiblePostResponses[keyof SearchBibleKeywordApiKeywordSearchBiblePostResponses];

export type ListBibleRootsApiKeywordSearchBibleRootsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/keyword-search/bible/roots';
};

export type ListBibleRootsApiKeywordSearchBibleRootsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBibleRootsApiKeywordSearchBibleRootsGetError = ListBibleRootsApiKeywordSearchBibleRootsGetErrors[keyof ListBibleRootsApiKeywordSearchBibleRootsGetErrors];

export type ListBibleRootsApiKeywordSearchBibleRootsGetResponses = {
    /**
     * Successful Response
     */
    200: BibleRootListResponse;
};

export type ListBibleRootsApiKeywordSearchBibleRootsGetResponse = ListBibleRootsApiKeywordSearchBibleRootsGetResponses[keyof ListBibleRootsApiKeywordSearchBibleRootsGetResponses];

export type GetBibleRootInfoApiKeywordSearchBibleRootRootGetData = {
    body?: never;
    path: {
        /**
         * Root
         */
        root: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/keyword-search/bible/root/{root}';
};

export type GetBibleRootInfoApiKeywordSearchBibleRootRootGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBibleRootInfoApiKeywordSearchBibleRootRootGetError = GetBibleRootInfoApiKeywordSearchBibleRootRootGetErrors[keyof GetBibleRootInfoApiKeywordSearchBibleRootRootGetErrors];

export type GetBibleRootInfoApiKeywordSearchBibleRootRootGetResponses = {
    /**
     * Successful Response
     */
    200: BibleKeywordSearchResponse;
};

export type GetBibleRootInfoApiKeywordSearchBibleRootRootGetResponse = GetBibleRootInfoApiKeywordSearchBibleRootRootGetResponses[keyof GetBibleRootInfoApiKeywordSearchBibleRootRootGetResponses];

export type GetBibleStatsApiKeywordSearchBibleStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/keyword-search/bible/stats';
};

export type GetBibleStatsApiKeywordSearchBibleStatsGetResponses = {
    /**
     * Successful Response
     */
    200: BibleStatsResponse;
};

export type GetBibleStatsApiKeywordSearchBibleStatsGetResponse = GetBibleStatsApiKeywordSearchBibleStatsGetResponses[keyof GetBibleStatsApiKeywordSearchBibleStatsGetResponses];

export type GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetData = {
    body?: never;
    path: {
        /**
         * Strongs Number
         */
        strongs_number: string;
    };
    query?: never;
    url: '/api/keyword-search/bible/cross-reference/{strongs_number}';
};

export type GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetError = GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetErrors[keyof GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetErrors];

export type GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetResponses = {
    /**
     * Successful Response
     */
    200: CrossReferenceResponse;
};

export type GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetResponse = GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetResponses[keyof GetCrossReferenceApiKeywordSearchBibleCrossReferenceStrongsNumberGetResponses];

export type LookupVerseApiVerseLookupGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Ref
         *
         * Verse reference: '2:183', 'Bakara 183', 'Genesis 1:1', etc.
         */
        ref: string;
        /**
         * Translator
         *
         * Quran translator (diyanet, yazir, ates, bulac, ozturk, vakfi, yildirim, yuksel)
         */
        translator?: 'diyanet' | 'yazir' | 'ates' | 'bulac' | 'ozturk' | 'vakfi' | 'yildirim' | 'yuksel' | 'arberry' | null;
    };
    url: '/api/verse/lookup';
};

export type LookupVerseApiVerseLookupGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LookupVerseApiVerseLookupGetError = LookupVerseApiVerseLookupGetErrors[keyof LookupVerseApiVerseLookupGetErrors];

export type LookupVerseApiVerseLookupGetResponses = {
    /**
     * Successful Response
     */
    200: VerseLookupResponse;
};

export type LookupVerseApiVerseLookupGetResponse = LookupVerseApiVerseLookupGetResponses[keyof LookupVerseApiVerseLookupGetResponses];

export type GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetData = {
    body?: never;
    path: {
        /**
         * Surah Id
         *
         * Surah ID (1-114)
         */
        surah_id: number;
        /**
         * Ayah Number
         *
         * Ayah number within the surah
         */
        ayah_number: number;
    };
    query?: never;
    url: '/api/quran/verses/{surah_id}/{ayah_number}/words';
};

export type GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetError = GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetErrors[keyof GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetErrors];

export type GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetResponses = {
    /**
     * Successful Response
     */
    200: VerseWordsResponse;
};

export type GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetResponse = GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetResponses[keyof GetVerseWordsApiQuranVersesSurahIdAyahNumberWordsGetResponses];

export type HandlePolarWebhookApiWebhooksPolarPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/webhooks/polar';
};

export type HandlePolarWebhookApiWebhooksPolarPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSubscriptionStatusApiSubscriptionStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/subscription/status';
};

export type GetSubscriptionStatusApiSubscriptionStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckApiHealthGetResponse = HealthCheckApiHealthGetResponses[keyof HealthCheckApiHealthGetResponses];

export type GetPublicConfigApiConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetPublicConfigApiConfigGetResponses = {
    /**
     * Successful Response
     */
    200: PublicConfigResponse;
};

export type GetPublicConfigApiConfigGetResponse = GetPublicConfigApiConfigGetResponses[keyof GetPublicConfigApiConfigGetResponses];
